// Privacy + extras: EXIF surfacing, redaction, dither, SVG trace.
//
//   npm run dev && npm run e2e:privacy
//
// photo-gps.jpg is generated by scripts/make-fixtures.mjs and carries planted GPS
// (53.5461 N, 113.4938 W) plus a Canon EOS R5 tag.
import { chromium } from "playwright";
import { fileURLToPath } from "node:url";
import path from "node:path";
import fs from "node:fs";
import os from "node:os";

const BASE = process.env.E2E_BASE ?? "http://localhost:5176";
const here = path.dirname(fileURLToPath(import.meta.url));
const FIXTURES = path.join(here, "fixtures");
const OUT = fs.mkdtempSync(path.join(os.tmpdir(), "image-lab-priv-"));

let failures = 0;
function check(name, pass, detail = "") {
  console.log(`${pass ? "  ok" : "FAIL"}  ${name}${detail ? ` — ${detail}` : ""}`);
  if (!pass) failures++;
}

async function pixel(page, fx, fy) {
  return page.evaluate(
    ([fx, fy]) => {
      const c = document.querySelector("canvas");
      const d = c
        .getContext("2d")
        .getImageData(Math.floor(c.width * fx), Math.floor(c.height * fy), 1, 1).data;
      return [d[0], d[1], d[2], d[3]];
    },
    [fx, fy],
  );
}

const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1400, height: 900 } });
page.on("pageerror", (e) => {
  console.log(`FAIL  pageerror — ${e.message}`);
  failures++;
});

await page.goto(BASE);
await page.setInputFiles('input[type="file"]', path.join(FIXTURES, "photo-gps.jpg"));
await page.waitForSelector("canvas");
await page.waitForTimeout(800);

// --- EXIF ---------------------------------------------------------------
const body = await page.textContent("body");
check("surfaces the planted GPS coordinates", /53\.5461/.test(body) && /113\.4938/.test(body));
check("names the camera", /Canon EOS R5/.test(body));
// The panel folds its warnings into one reserved line, so a GPS file states the drop
// promise as part of the GPS warning rather than on a line of its own.
check("promises the export drops the metadata", /export drops/i.test(body));

// --- redact -------------------------------------------------------------
await page.click('[data-tool="redact"]');
await page.waitForTimeout(400);
const before = await pixel(page, 0.5, 0.3);

const box = await page.locator("canvas").boundingBox();
await page.mouse.move(box.x + box.width * 0.35, box.y + box.height * 0.15);
await page.mouse.down();
await page.mouse.move(box.x + box.width * 0.65, box.y + box.height * 0.45, { steps: 6 });
await page.mouse.up();
await page.waitForTimeout(700);

const after = await pixel(page, 0.5, 0.3);
const changed =
  Math.abs(after[0] - before[0]) + Math.abs(after[1] - before[1]) + Math.abs(after[2] - before[2]);
check("dragging a box redacts that area", changed > 6, `rgb(${before.slice(0,3)}) -> rgb(${after.slice(0,3)})`);

const outside = await pixel(page, 0.05, 0.9);
check("redaction leaves the rest of the image alone", outside[3] === 255);
check("region count is reported", /1 box/.test(await page.textContent("body")));

// Redaction must survive to full-resolution export, not just the preview — a
// normalized-geometry bug here means leaking exactly what you meant to hide.
const [dl] = await Promise.all([
  page.waitForEvent("download", { timeout: 60000 }),
  page.click('button:has-text("Download")'),
]);
const saved = path.join(OUT, dl.suggestedFilename());
await dl.saveAs(saved);
check("redacted export downloads", fs.statSync(saved).size > 0, dl.suggestedFilename());

await page.click('li:has-text("Redact") button[title="Remove"]');
await page.waitForTimeout(400);

// --- dither -------------------------------------------------------------
await page.click('[data-tool="dither"]');
await page.waitForTimeout(900);
const levels = await page.evaluate(() => {
  const c = document.querySelector("canvas");
  const d = c.getContext("2d").getImageData(0, 0, c.width, c.height).data;
  const seen = new Set();
  for (let i = 0; i < d.length; i += 4) seen.add(d[i]);
  return seen.size;
});
// Default is 2 levels monochrome, so the red channel should hold ~2 distinct values.
check("dither quantises to 2 levels", levels <= 3, `${levels} distinct values in R`);
await page.click('li:has-text("Dither") button[title="Remove"]');
await page.waitForTimeout(400);

// --- SVG trace ----------------------------------------------------------
await page.click('button:has-text("SVG")');
await page.waitForTimeout(300);
const [svgDl] = await Promise.all([
  page.waitForEvent("download", { timeout: 120000 }),
  page.click('button:has-text("Download")'),
]);
const svgPath = path.join(OUT, svgDl.suggestedFilename());
await svgDl.saveAs(svgPath);
const svg = fs.readFileSync(svgPath, "utf8");
// Not startsWith("<svg"): VTracer emits an XML prolog and a generator comment first.
check("SVG export produces real vector markup", svg.includes("<svg") && svg.includes("<path"), `${(svg.length / 1024).toFixed(0)}KB, ${(svg.match(/<path/g) || []).length} paths`);
check("SVG filename has the right extension", svgDl.suggestedFilename().endsWith(".svg"));

await browser.close();
console.log(failures ? `\n${failures} failing` : "\nall passing");
process.exit(failures ? 1 : 0);
